### ISSUE TITLE
Issue with docker-compose startup

### ISSUE THREAD

**Issue by ilocit** [hpi-schul-cloud/docker-compose#30]
I was able to create a local git and pull the docker-compose repo.
When starting the server via `sudo ./startup_develop.sh up -d server`, I get the following message:

```
./startup_develop.sh: 2: source: not found
./startup_develop.sh: 3: source: not found
WARNING: The SERVER_DOCKER_TAG variable is not set. Defaulting to a blank string.
WARNING: The CLIENT_DOCKER_TAG variable is not set. Defaulting to a blank string.
WARNING: The NUXT_DOCKER_TAG variable is not set. Defaulting to a blank string.
WARNING: The SERVER_PATH variable is not set. Defaulting to a blank string.
WARNING: The CLIENT_PATH variable is not set. Defaulting to a blank string.
WARNING: The NUXT_PATH variable is not set. Defaulting to a blank string.
Pulling mongodb (mongo:latest)...
latest: Pulling from library/mongo
f22ccc0b8772: Pull complete
3cf8fb62ba5f: Pull complete
e80c964ece6a: Pull complete
329e632c35b3: Pull complete
3e1bd1325a3d: Pull complete
4aa6e3d64a4a: Pull complete
035bca87b778: Pull complete
874e4e43cb00: Pull complete
08cb97662b8b: Pull complete
f623ce2ba1e1: Pull complete
f100ac278196: Pull complete
b16ea696739f: Pull complete
Digest: sha256:d54fb51a493131117a8b85a2d46ed7d64a2cb79607fb3ce350d1722c0cafc812
Status: Downloaded newer image for mongo:latest
Building calendar
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 542, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 366, in ensure_image_exists
    self.build(cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1084, in build
    build_output = builder.build(
  File "/usr/lib/python3/dist-packages/docker/api/build.py", line 148, in build
    raise TypeError("You must specify a directory to build in path")
TypeError: You must specify a directory to build in path
```
Any idea what might be wrong with the `calendar `module?
Thanks so much!
_Matthias_

**Comment by janrenz** [comment]
This might be related with some limits we ran into on docker hub registry. Please try again later today ...

**Comment by ilocit** [comment]
Thanks a mil, Jan, for the super swift reply. I will try again later today.

**Comment by ilocit** [comment]
Sorry, but even after a new pull today, the same error still occures...any other idea? Thx so much!

**Comment by CordlessWool** [comment]
It wants to build so it should not relate to the repo.
The problem is that it could not find a folder with the name. Should be solved with this pull request: https://github.com/hpi-schul-cloud/docker-compose/pull/26. You can also use it now, should work. But maybe the last changes are not already included but you can prevent this by doing a pull at first: `./startup_develop.sh pull`

**Comment by ilocit** [comment]
Thanks for the update @CordlessWool I did another Pull and created some folders too. 
But once the pull completed, I still get an error message. A different one now, but still an error ;-)

`ERROR: no such image: schulcloud/schulcloud-server:: invalid reference format`

**Comment by CordlessWool** [comment]
This error pops up with the `./startup_develop.sh`? The problem here is that the image tag is not set, but should normaly defined in `./envs/develop.env`:

`NUXT_DOCKER_TAG=develop_latest
SERVER_DOCKER_TAG=develop_latest
CLIENT_DOCKER_TAG=develop_latest`

**Comment by ilocit** [comment]
Exactly, I am using `./startup_end-to-end-tests.sh` and everything should be set, but the above is the output / error I keep receiving.
All the needed container are being pulled, but then the error about the missing image is throuwn..

Now the output is even different. I don't know, maybe it is too long for me to remember what I did different last time....jumping from so many topics back to this one....sorry.

```
matthias@ilocit-ubuntu-docker:~/hpi-schul-cloud$ ls -al
total 68
drwxrwxr-x  7 matthias matthias 4096 Dec 10 14:46 .
drwxr-xr-x 11 matthias matthias 4096 Dec 10 14:46 ..
-rw-rw-r--  1 matthias matthias  431 Dec  1 20:06 CHANGELOG.md
drwxrwxr-x  2 matthias matthias 4096 Dec  1 20:14 compose-files
drwxrwxr-x  4 matthias matthias 4096 Dec  1 20:06 data
-rw-rw-r--  1 matthias matthias 3744 Dec  1 20:06 docker-compose.end-to-end-tests-Build.yml
-rw-rw-r--  1 matthias matthias 4922 Dec  1 20:06 docker-compose.end-to-end-tests.yml
-rw-rw-r--  1 matthias matthias 3744 Dec  1 20:06 docker-compose.integration-test-Build.yml
-rw-rw-r--  1 matthias matthias 4922 Dec  1 20:06 docker-compose.integration-test.yml
drwxrwxr-x  2 matthias matthias 4096 Dec 10 14:44 **envs**
drwxrwxr-x  8 matthias matthias 4096 Dec  1 20:49 .git
drwxrwxr-x  3 matthias matthias 4096 Dec  1 20:06 .github
-rw-rw-r--  1 matthias matthias   14 Dec  1 20:06 .gitignore
-rw-rw-r--  1 matthias matthias 1071 Dec  1 20:06 README.md
-rwxrwxr-x  1 matthias matthias  447 Dec  1 20:18 startup_develop.sh

matthias@ilocit-ubuntu-docker:~/hpi-schul-cloud$ cat ./envs/develop.env

# do not add secrets here, for secrets and own configuraton
# add a .env file, that will not commit to git
NODE_ENV=development
NUXT_DOCKER_TAG=develop_latest
SERVER_DOCKER_TAG=develop_latest
CLIENT_DOCKER_TAG=develop_latest
COMPOSE_FILES_PATH=compose-files
NUXT_PATH=../../nuxt-client
SERVER_PATH=../../schulcloud-server
CLIENT_PATH=../../schulcloud-client
FILE_PREVIEW_PATH=../../filepreview
NOTIFICATION_SERVICE_PATH=../../node-notification-service
CALENDAR_PATH=../../schulcloud-calendar

matthias@ilocit-ubuntu-docker:~/hpi-schul-cloud$ sudo ./startup_develop.sh up -d server

./startup_develop.sh: 2: source: not found
./startup_develop.sh: 3: source: not found
WARNING: The SERVER_DOCKER_TAG variable is not set. Defaulting to a blank string.
WARNING: The CLIENT_DOCKER_TAG variable is not set. Defaulting to a blank string.
WARNING: The NUXT_DOCKER_TAG variable is not set. Defaulting to a blank string.
WARNING: The SERVER_PATH variable is not set. Defaulting to a blank string.
WARNING: The CLIENT_PATH variable is not set. Defaulting to a blank string.
WARNING: The NUXT_PATH variable is not set. Defaulting to a blank string.
ERROR: no such image: schulcloud/schulcloud-server:: invalid reference format
```

**Comment by CordlessWool** [comment]
You run this on git bash? Because in develp.env the envs are set to I confused why it say they are not defined. The sh file should export the envs so docker-compose can use them and you said it also already pulled? Also server, client and co or only mongodb, postgres and otherstuff where default envs are set

**Comment by ilocit** [comment]
I run this in `bash `on Ubuntu. git bash on WIndows did not work for me, since I would need to install docker there first.

**Comment by CordlessWool** [comment]
I started testing it on my linux machine, but I use there podman instead of docker as executer and I have problems relating to this. I will need some more time but I will try it on Ubuntu.

**Comment by ilocit** [comment]
No rush, I am glad you are following up and spending time on this at all!

**Comment by ilocit** [comment]
Actually, as a "compensation", if you need translations for HPI Schul Cloud, I am happy to donate time and our resources! 
We are also an SAP Affiliate...
